Lambda-School-Labs/community-calendar-be

- index.js
> remove dotenv for production

- notes/prisma_auth0.md
Replaces Heroku Env Var example image to include PRISMA Var
> Updates image

- auth/authenticate.js
- graphql/resolvers.js
- notes/auth0_login.html
- notes/auth0_rule.js
- notes/prisma_auth0.md
Add Prisma bindings to events in resolvers to fix the issue of some connected fields returning null.  Updated the auth0_login in notes.
> Prisma bindings login

- notes/auth0_login.html
Updated the login form in `./notes/auth0_login.html` to match UX design spec.
> Update login form

- graphql/resolvers.js
- graphql/schema.graphql
Added where, orderBy, skip, after, before, first, and last arguments to queries schema/resolvers.
> added arguments to queries

- graphql/resolvers.js
- graphql/schema.graphql
- prisma-client/data/seed.graphql
- prisma-client/datamodel.prisma
- prisma-client/generated/prisma-client/index.d.ts
- prisma-client/generated/prisma-client/index.js
- prisma-client/generated/prisma-client/prisma-schema.js
- prisma-client/generated/prisma.graphql
Added a "tags" field to events in the DB. Updated the prisma datamodel, udpated the gql schema, updated resolvers, updated seed data.
> Event tags

- graphql/resolvers.js
- graphql/schema.graphql
- package.json
Added RSVPS and fixed tags schema
> Tags schema

- README.md
backend documentation includes markdown of application architecture and link to the Prisma / Auth0 bootstrap PDF
>  backend documentation

- notes/auth0_login.html
Co-authored-by: Tyler Berrett <btylerberrett@gmail.com>
> fixed go back button for auth0 login

- auth/authenticate.js
- notes/auth0_login.html
Co-authored-by: Tyler Berrett <btylerberrett@gmail.com>
> added error messages and error handling for signup/signin

- graphql/resolvers.js
- graphql/schema.graphql
- index.js
- notes/auth0_login.html
- notes/auth0_rule.js
Lowell and I updated the event create input schema.  Tags is now sent as just an array of tag objects with just the title field.  The resolver will automatically determine which tags are stored in the database and connect the event to them or create new tags.  Tags are converted to lowercase before they are stored in the database.
> Add events tags

- README.md
- graphql/resolvers.js
- graphql/schema.graphql
- index.js
- package-lock.json
- package.json
- prisma-client/datamodel.prisma
- ticket-master/tm.datasource.js
- ticket-master/tm.schema.graphql
installed new npm package to query REST apis from apollo.
Created a datasource class which interacts with the Ticket Master API.
Added the datasource to the ApolloServer instance so resolvers could use the API.
Made a resolver to return data from the ticketmaster API
> Add Ticket Master API as endpoint

- prisma-client/data/seed.graphql
- prisma-client/datamodel.prisma
Co-authored-by: Westley Strellis <wstrellis@gmail.com>
> change lat/long to float and seed coordinates

- graphql/schema.graphql
- prisma-client/data/seed.graphql
- prisma-client/datamodel.prisma
- prisma-client/generated/prisma-client/index.d.ts
- prisma-client/generated/prisma-client/index.js
- prisma-client/generated/prisma-client/prisma-schema.js
- prisma-client/generated/prisma.graphql
Updated datamodel.prisma, prisma seeds, and apollo schema.graphql. All prisma services will have to reset, redeploy, reseed.
> add TicketType as enum and field of Event

- graphql/resolvers.js
point() method expected [long,lat] be we were using [lat,long].
> fixed distance calculation

- graphql/resolvers.js
Convert tags array to an object before sending to prisma.
> Update events resolver tags

- README.md
- auth/authenticate.js
- graphql/helpers.js
- graphql/resolvers.js
- graphql/schema.js
- index.js
- notes/auth0.md
- notes/auth0_login.html
- notes/auth0_rule.js
- notes/prisma_auth0.md
- prisma-client/data/seed.graphql
- prisma-client/datamodel.prisma
- prisma-client/generated/prisma-client/index.d.ts
- prisma-client/generated/prisma-client/index.js
- prisma-client/generated/prisma-client/prisma-schema.js
- prisma-client/generated/prisma.graphql
- changed ticketType to ticketPrice, it is now a float
- updated documentation and added comments throughout code
- updated seeds
> changed ticketType to ticketPrice, updated documentation

- graphql/schema.graphql
> fixed schema for ticketPrice

- graphql/resolvers.js
- graphql/schema.graphql
- prisma-client/data/seed.graphql
- Added query for logged in user
- Updated seeds to include user profile images
> added profile images to user seeds, added user query

- prisma-client/data/seed.graphql
Seeds populate on developer instance, ready for review and merge
> add recurring event seeds

- graphql/resolvers.js
- graphql/schema.js
Fixed a bug where ticket prices were not being filtered correctly.
> fixed ticket price filter bug

- README.md
- notes/auth0_rule.js
- Updated queries/mutations in readme
- Updated Auth0 rule
> update readme and auth0 rule

- Makefile
Changes the way the .env file is processed. Instead of exporting _all_ variables, only export the variables read in from the .env file. When you export _all_ variables by just using `export` without arguments, it forces Make to resolve _all_ variables, which defeats the purpose of recursively expanded variables.
Added a check to prepend the environment name on the application domain when the environment is not production.
Refactored the variables that require a call to AWS as '[thunks](http://www.cakoose.com/wiki/gnu_make_thunks)' to prevent them from being evaluated until used.
> Fixes issue with non-production environments

- prisma/seed.js
Updated seeded data so that the test events will always be in the future when the data is reseeded. There is a lot of code changed from prettier updating, but my actual changes in the code include adding the dates defined in lines 129-208 and updates to the date variables in each of the 11 events in lines 210-687
> Seeded data always in the future

- apollo/src/__tests__/Mutation.js
- apollo/src/__tests__/Query.spec.js
- apollo/src/context/__mocks__/index.js
This pull requests adds tests for the mutation and query resolvers, and adds a mockfile for context. 
Remove any items which are not applicable.
> adds tests for mutations and queries, adds mockfile in context

- apollo/src/resolvers/Mutation.js
- prisma/prisma-datamodel.graphql
This feature adds the functionality for deleting a series and all of the events tied to that series
Remove any items which are not applicable.
> adds delete functionality for deleting a series

- apollo/src/resolvers/Mutation.js
This feature adds the backend functionality for editing events in a series
Remove any items which are not applicable.
> add functionality on the backend for editing events in series

- prisma/prisma-datamodel.graphql
This pull request fixes an error in the data model that deleted all events in a series when trying to delete a single event that is part of a series. 
Please delete options that are not relevant.
> fixes cascading delete of events when deleting single event
